version: '3.8'

services:
  blockchain-services:
    environment:
      - ADMIN_DASHBOARD_LOCAL_ONLY=${BCHAIN_ADMIN_DASHBOARD_LOCAL_ONLY:-true}
      - ADMIN_DASHBOARD_ALLOW_PRIVATE=${BCHAIN_ADMIN_DASHBOARD_ALLOW_PRIVATE:-true}
      - SECURITY_ALLOW_PRIVATE_NETWORKS=${BCHAIN_SECURITY_ALLOW_PRIVATE_NETWORKS:-true}
      - TREASURY_TOKEN=${TREASURY_TOKEN:-}
      - TREASURY_TOKEN_HEADER=${TREASURY_TOKEN_HEADER:-X-Access-Token}
      - TREASURY_TOKEN_COOKIE=${TREASURY_TOKEN_COOKIE:-access_token}
      - TREASURY_TOKEN_REQUIRED=${TREASURY_TOKEN_REQUIRED:-true}
