version: '3.8'

services:
  blockchain-services:
    environment:
      - ADMIN_DASHBOARD_LOCAL_ONLY=${BCHAIN_ADMIN_DASHBOARD_LOCAL_ONLY:-true}
      - ADMIN_DASHBOARD_ALLOW_PRIVATE=${BCHAIN_ADMIN_DASHBOARD_ALLOW_PRIVATE:-true}
      - SECURITY_ALLOW_PRIVATE_NETWORKS=${BCHAIN_SECURITY_ALLOW_PRIVATE_NETWORKS:-true}
      - SECURITY_ACCESS_TOKEN=${BCHAIN_SECURITY_ACCESS_TOKEN:-}
      - SECURITY_ACCESS_TOKEN_HEADER=${BCHAIN_SECURITY_ACCESS_TOKEN_HEADER:-X-Access-Token}
      - SECURITY_ACCESS_TOKEN_COOKIE=${BCHAIN_SECURITY_ACCESS_TOKEN_COOKIE:-access_token}
      - SECURITY_ACCESS_TOKEN_REQUIRED=${BCHAIN_SECURITY_ACCESS_TOKEN_REQUIRED:-true}
