version: '3.8'

services:
  blockchain-services:
    environment:
      - ADMIN_DASHBOARD_LOCAL_ONLY=${BCHAIN_ADMIN_DASHBOARD_LOCAL_ONLY:-true}
      - ADMIN_DASHBOARD_ALLOW_PRIVATE=${BCHAIN_ADMIN_DASHBOARD_ALLOW_PRIVATE:-true}
      - SECURITY_ALLOW_PRIVATE_NETWORKS=${BCHAIN_SECURITY_ALLOW_PRIVATE_NETWORKS:-true}
      - SECURITY_INTERNAL_TOKEN=${BCHAIN_SECURITY_INTERNAL_TOKEN:-}
      - SECURITY_INTERNAL_TOKEN_HEADER=${BCHAIN_SECURITY_INTERNAL_TOKEN_HEADER:-X-Internal-Token}
      - SECURITY_INTERNAL_TOKEN_COOKIE=${BCHAIN_SECURITY_INTERNAL_TOKEN_COOKIE:-internal_token}
      - SECURITY_INTERNAL_TOKEN_REQUIRED=${BCHAIN_SECURITY_INTERNAL_TOKEN_REQUIRED:-true}
