version: '3.8'

services:
  blockchain-services:
    environment:
      - ADMIN_DASHBOARD_LOCAL_ONLY=${ADMIN_DASHBOARD_LOCAL_ONLY:-true}
      - ADMIN_DASHBOARD_ALLOW_PRIVATE=${ADMIN_DASHBOARD_ALLOW_PRIVATE:-true}
      - SECURITY_ALLOW_PRIVATE_NETWORKS=${SECURITY_ALLOW_PRIVATE_NETWORKS:-true}
      - SECURITY_INTERNAL_TOKEN_REQUIRED=${SECURITY_INTERNAL_TOKEN_REQUIRED:-true}
